/* 戰鬥特效引擎＋每位角色專屬的技能動畫編排 */
const FXE = (() => {
  let cv, cx, list = [], raf = 0, last = 0, W = 0, H = 0, dpr = 1;
  const R = (a, b) => a + Math.random() * (b - a);
  function ensure() {
    if (!cv) { cv = document.getElementById('bCanvas'); cx = cv.getContext('2d'); }
    const r = cv.parentElement.getBoundingClientRect(); dpr = Math.min(2, window.devicePixelRatio || 1);
    if (cv.width !== Math.round(r.width * dpr) || cv.height !== Math.round(r.height * dpr)) { cv.width = Math.round(r.width * dpr); cv.height = Math.round(r.height * dpr); }
    W = r.width; H = r.height;
  }
  function add(e) { ensure(); e.t = 0; e.life = e.life || .6; list.push(e); if (!raf) { last = performance.now(); raf = requestAnimationFrame(loop); } return e; }
  function loop(now) {
    const dt = Math.min(.05, (now - last) / 1000); last = now;
    cx.setTransform(dpr, 0, 0, dpr, 0, 0); cx.clearRect(0, 0, W, H);
    list = list.filter(e => { e.t += dt; const k = Math.min(1, e.t / e.life); cx.save(); if (e.add) cx.globalCompositeOperation = 'lighter'; try { e.draw(cx, k, dt, e.t); } catch (err) { } cx.restore(); return e.t < e.life; });
    if (list.length) raf = requestAnimationFrame(loop); else { raf = 0; cx.clearRect(0, 0, W, H); }
  }
  function clear() { list = []; }
  const ease = { out: k => 1 - Math.pow(1 - k, 3), in: k => k * k * k, io: k => k < .5 ? 4 * k * k * k : 1 - Math.pow(-2 * k + 2, 3) / 2 };
  const fade = (k, a, b) => k < a ? k / a : k > b ? Math.max(0, (1 - k) / (1 - b)) : 1;
  function glow(c, color, blur) { c.shadowColor = color; c.shadowBlur = blur; }
  function jag(x1, y1, x2, y2, seg, amp) { const pts = [[x1, y1]]; for (let i = 1; i < seg; i++) { const t = i / seg; const nx = -(y2 - y1), ny = x2 - x1, l = Math.hypot(nx, ny) || 1; const o = R(-amp, amp); pts.push([x1 + (x2 - x1) * t + nx / l * o, y1 + (y2 - y1) * t + ny / l * o]); } pts.push([x2, y2]); return pts; }
  function path(c, pts) { c.beginPath(); c.moveTo(pts[0][0], pts[0][1]); for (let i = 1; i < pts.length; i++) c.lineTo(pts[i][0], pts[i][1]); }

  /* ---------- 基本元件 ---------- */
  const P = {
    flash(color, life, a) { return add({ life: life || .3, draw(c, k) { c.globalAlpha = (a || .7) * (1 - k); c.fillStyle = color; c.fillRect(0, 0, W, H); } }); },
    tint(color, life, a) { return add({ life, draw(c, k) { c.globalAlpha = (a || .3) * fade(k, .15, .7); c.fillStyle = color; c.fillRect(0, 0, W, H); } }); },
    bolt(x1, y1, x2, y2, o) { o = o || {}; let pts = jag(x1, y1, x2, y2, 12, o.amp || 26), acc = 0; return add({ add: true, life: o.life || .35, draw(c, k, dt) { acc += dt; if (acc > .045) { acc = 0; pts = jag(x1, y1, x2, y2, 12, o.amp || 26); } c.globalAlpha = 1 - k; c.lineJoin = 'round'; glow(c, o.color || '#7fd4ff', 22); c.strokeStyle = o.color || '#7fd4ff'; c.lineWidth = (o.w || 6); path(c, pts); c.stroke(); c.shadowBlur = 0; c.strokeStyle = '#fff'; c.lineWidth = (o.w || 6) * .35; c.stroke(); if (o.branch !== false) { const b = pts[5]; path(c, jag(b[0], b[1], b[0] + R(-60, 60), b[1] + R(20, 80), 5, 10)); c.lineWidth = 2; c.stroke(); } } }); },
    beam(x1, y1, x2, y2, o) { o = o || {}; return add({ add: true, life: o.life || .5, draw(c, k) { const w = (o.w || 26) * Math.sin(Math.min(1, k * 1.4) * Math.PI) + 2, g = c.createLinearGradient(x1, y1, x2, y2); g.addColorStop(0, o.c1 || '#fff'); g.addColorStop(1, o.c2 || '#6fd3ff'); const reach = Math.min(1, k * 4); c.lineCap = 'round'; glow(c, o.c2 || '#6fd3ff', 30); c.strokeStyle = g; c.lineWidth = w; c.beginPath(); c.moveTo(x1, y1); c.lineTo(x1 + (x2 - x1) * reach, y1 + (y2 - y1) * reach); c.stroke(); c.shadowBlur = 0; c.strokeStyle = '#fff'; c.lineWidth = w * .3; c.stroke(); } }); },
    ring(x, y, o) { o = o || {}; return add({ add: o.add !== false, life: o.life || .5, draw(c, k) { const r = (o.r0 || 10) + ((o.r1 || 140) - (o.r0 || 10)) * ease.out(k); c.globalAlpha = 1 - k; c.strokeStyle = o.color || '#fff'; c.lineWidth = (o.w || 8) * (1 - k) + 1; glow(c, o.color || '#fff', 16); c.beginPath(); c.ellipse(x, y, r, r * (o.flat || 1), 0, 0, Math.PI * 2); c.stroke(); } }); },
    burst(x, y, o) { o = o || {}; return add({ add: true, life: o.life || .35, draw(c, k) { const r = (o.r || 90) * ease.out(k), g = c.createRadialGradient(x, y, 0, x, y, r); g.addColorStop(0, `rgba(255,255,255,${1 - k})`); g.addColorStop(.35, o.color || 'rgba(255,170,90,.9)'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.globalAlpha = 1 - k * .6; c.fillStyle = g; c.beginPath(); c.arc(x, y, r, 0, Math.PI * 2); c.fill(); } }); },
    particles(o) {
      const ps = []; for (let i = 0; i < o.n; i++) { const a = R(o.ang ? o.ang[0] : 0, o.ang ? o.ang[1] : Math.PI * 2), s = R(o.spd[0], o.spd[1]); ps.push({ x: o.x + R(-(o.jx || 0), o.jx || 0), y: o.y + R(-(o.jy || 0), o.jy || 0), vx: Math.cos(a) * s, vy: Math.sin(a) * s, l: R(o.life[0], o.life[1]), s: R(o.size[0], o.size[1]), c: o.colors[i % o.colors.length], r: R(0, 6), vr: R(-6, 6), d: R(0, o.delay || 0) }); }
      return add({ add: o.add, life: o.life[1] + (o.delay || 0) + .05, draw(c, k, dt, t) {
        for (const p of ps) { const lt = t - p.d; if (lt < 0 || lt > p.l) continue; if (o.toward) { p.vx += (o.toward.x - p.x) * dt * (o.pull || 6); p.vy += (o.toward.y - p.y) * dt * (o.pull || 6); } p.vy += (o.g || 0) * dt; p.vx *= 1 - (o.drag || 0) * dt; p.vy *= 1 - (o.drag || 0) * dt; p.x += p.vx * dt; p.y += p.vy * dt; p.r += p.vr * dt;
          const a = 1 - lt / p.l; c.globalAlpha = a; c.fillStyle = p.c;
          if (o.shape === 'petal') { c.save(); c.translate(p.x, p.y); c.rotate(p.r); c.beginPath(); c.ellipse(0, 0, p.s, p.s * .5, 0, 0, Math.PI * 2); c.fill(); c.restore(); }
          else if (o.shape === 'spark') { c.strokeStyle = p.c; c.lineWidth = p.s * .5; c.beginPath(); c.moveTo(p.x, p.y); c.lineTo(p.x - p.vx * .04, p.y - p.vy * .04); c.stroke(); }
          else if (o.shape === 'shard') { c.save(); c.translate(p.x, p.y); c.rotate(p.r); c.beginPath(); c.moveTo(0, -p.s); c.lineTo(p.s * .45, 0); c.lineTo(0, p.s); c.lineTo(-p.s * .45, 0); c.closePath(); c.fill(); c.restore(); }
          else if (o.shape === 'note') { c.font = `700 ${p.s * 2.2}px serif`; c.fillText(i2note(p), p.x, p.y); }
          else { c.beginPath(); c.arc(p.x, p.y, p.s * (o.shrink ? a : 1), 0, Math.PI * 2); c.fill(); } }
      } });
    },
    text(x, y, str, o) { o = o || {}; return add({ life: o.life || .8, draw(c, k) { const s = k < .15 ? .4 + k / .15 * .8 : 1.2 - Math.min(.2, (k - .15)); c.globalAlpha = fade(k, .08, .7); c.translate(x, y); c.rotate(o.rot || -.12); c.scale(s, s); c.font = `900 ${o.size || 64}px "Noto Serif TC",serif`; c.textAlign = 'center'; c.textBaseline = 'middle'; c.lineJoin = 'round'; c.lineWidth = 10; c.strokeStyle = o.stroke || '#1a0a08'; c.strokeText(str, 0, 0); c.fillStyle = o.color || '#fff4c8'; c.fillText(str, 0, 0); } }); },
    arm(x1, y1, x2, y2, o) { o = o || {}; const dir = Math.sign(x2 - x1) || 1; return add({ life: o.life || .45, draw(c, k) {
      const ext = k < .45 ? ease.out(k / .45) : k < .6 ? 1 : 1 - ease.in((k - .6) / .4); const tx = x1 + (x2 - x1) * ext, ty = y1 + (y2 - y1) * ext;
      c.lineCap = 'round'; c.strokeStyle = o.sleeve || '#c8322b'; c.lineWidth = 22; c.beginPath(); c.moveTo(x1, y1); c.lineTo(x1 + dir * 26, y1); c.stroke();
      c.strokeStyle = o.skin || '#f0b98a'; c.lineWidth = o.w || 14; c.beginPath(); c.moveTo(x1 + dir * 20, y1); c.lineTo(tx, ty); c.stroke();
      c.strokeStyle = 'rgba(255,255,255,.55)'; c.lineWidth = 2; for (let i = 0; i < 3; i++) { const yy = ty + (i - 1) * 14; c.beginPath(); c.moveTo(tx - dir * 60, yy); c.lineTo(tx - dir * 100, yy); c.stroke(); }
      if (o.haki) glow(c, '#ff3b2f', 18); c.fillStyle = o.haki ? '#1b1b22' : (o.skin || '#f0b98a'); c.beginPath(); c.arc(tx, ty, o.fist || 18, 0, Math.PI * 2); c.fill(); c.strokeStyle = o.haki ? '#ff5a4a' : '#8a4a2a'; c.lineWidth = 3; c.stroke();
    } }); },
    snake(x1, y1, x2, y2, o) { o = o || {}; const pts = []; for (let i = 0; i <= 60; i++) { const t = i / 60; pts.push([x1 + (x2 - x1) * t, y1 + (y2 - y1) * t + Math.sin(t * Math.PI * 3) * 70 * Math.sin(t * Math.PI)]); } return add({ life: o.life || .6, draw(c, k) {
      const n = Math.max(2, Math.floor(pts.length * Math.min(1, k / .55))), sub = k < .8 ? pts.slice(0, n) : pts.slice(Math.floor((k - .8) / .2 * pts.length), n);
      if (sub.length < 2) return; c.lineCap = 'round'; c.lineJoin = 'round'; glow(c, '#ff2b2b', 16); c.strokeStyle = '#140d10'; c.lineWidth = 18; path(c, sub); c.stroke(); c.shadowBlur = 0; c.strokeStyle = '#6a1a1a'; c.lineWidth = 4; c.stroke();
      const e = sub[sub.length - 1]; c.fillStyle = '#140d10'; glow(c, '#ff2b2b', 20); c.beginPath(); c.arc(e[0], e[1], 22, 0, Math.PI * 2); c.fill(); } }); },
    slash(x, y, o) { o = o || {}; const a0 = o.a || -.9, span = o.span || 1.8, r = o.r || 110; return add({ add: true, life: o.life || .3, draw(c, k) { const p = ease.out(Math.min(1, k * 1.8)); c.globalAlpha = 1 - k; glow(c, o.color || '#fff', 20); c.strokeStyle = o.color || '#fff'; c.lineCap = 'round'; for (let i = 0; i < 3; i++) { c.lineWidth = (o.w || 10) - i * 3; c.beginPath(); c.arc(x, y, r - i * 6, a0, a0 + span * p, o.ccw); c.stroke(); } } }); },
    crescent(x1, y1, x2, y2, o) { o = o || {}; return add({ add: true, life: o.life || .4, draw(c, k) { const e = ease.io(k), x = x1 + (x2 - x1) * e, y = y1 + (y2 - y1) * e, s = o.size || 60, d = Math.sign(x2 - x1) || 1; c.globalAlpha = 1 - k * .5; glow(c, o.color || '#ffd27a', 20); c.fillStyle = o.color || '#ffd27a'; c.beginPath(); c.ellipse(x, y, s * .45, s, 0, -Math.PI / 2, Math.PI / 2, d < 0); c.ellipse(x - d * s * .2, y, s * .25, s * .85, 0, Math.PI / 2, -Math.PI / 2, d > 0); c.fill(); } }); },
    vortex(x, y, o) { o = o || {}; return add({ add: o.add, life: o.life || 1, draw(c, k, dt, t) { const r = (o.r || 90) * Math.min(1, k * 4) * (k > .8 ? (1 - k) / .2 : 1); c.translate(x, y); c.scale(1, o.flat || 1); for (let a = 0; a < (o.arms || 5); a++) { c.beginPath(); for (let i = 0; i < 40; i++) { const q = i / 40, ang = a / (o.arms || 5) * Math.PI * 2 + q * 4 + t * (o.spin || 8); const rr = r * q; i ? c.lineTo(Math.cos(ang) * rr, Math.sin(ang) * rr) : c.moveTo(0, 0); } c.strokeStyle = o.color || '#5a2a8a'; c.lineWidth = o.w || 8; c.globalAlpha = .85; c.stroke(); } const g = c.createRadialGradient(0, 0, 0, 0, 0, r * .6); g.addColorStop(0, o.core || '#000'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.beginPath(); c.arc(0, 0, r * .6, 0, Math.PI * 2); c.fill(); } }); },
    tornado(x, y, o) { o = o || {}; return add({ life: o.life || 1.2, draw(c, k, dt, t) { const h = (o.h || 260) * Math.min(1, k * 3); c.globalAlpha = fade(k, .1, .75) * .85; for (let i = 0; i < 16; i++) { const q = i / 16, yy = y - q * h, w = 20 + q * (o.w || 120), off = Math.sin(t * 9 + i * .7) * 16 * q; c.strokeStyle = i % 2 ? (o.c1 || '#d9b064') : (o.c2 || '#a9803e'); c.lineWidth = 7; c.beginPath(); c.ellipse(x + off, yy, w, w * .22, 0, 0, Math.PI * 2); c.stroke(); } } }); },
    cracks(x, y, o) { o = o || {}; const lines = []; for (let i = 0; i < (o.n || 9); i++) { const a = R(0, Math.PI * 2); lines.push(jag(x, y, x + Math.cos(a) * R(80, o.len || 220), y + Math.sin(a) * R(80, o.len || 220), 6, 14)); } return add({ life: o.life || .9, draw(c, k) { c.globalAlpha = 1 - ease.in(k); c.lineJoin = 'miter'; glow(c, '#fff', 10); c.strokeStyle = o.color || '#f4f7ff'; lines.forEach((l, i) => { c.lineWidth = 3.5 - (i % 3); path(c, l.slice(0, Math.ceil(l.length * Math.min(1, k * 6)))); c.stroke(); }); } }); },
    hand(c, x, y, ang, s, skin, sleeve, grip) { c.save(); c.translate(x, y); c.rotate(ang); c.scale(s, s); c.fillStyle = sleeve; c.fillRect(-7, 0, 14, 38); c.fillStyle = skin; c.fillRect(-6, -18, 12, 20); c.beginPath(); c.ellipse(0, -24, 11, 10, 0, 0, Math.PI * 2); c.fill(); const f = grip ? .4 : 1; for (let i = 0; i < 4; i++) { c.beginPath(); c.ellipse(-7.5 + i * 5, -34 * (grip ? .85 : 1) - (i === 1 || i === 2 ? 3 : 0) * f, 2.4, 7 * f, 0, 0, Math.PI * 2); c.fill(); } c.beginPath(); c.ellipse(11, -22, 2.6, 6, .8, 0, Math.PI * 2); c.fill(); c.restore(); },
    hands(x, y, o) { o = o || {}; const hs = []; for (let i = 0; i < (o.n || 10); i++) hs.push({ a: R(0, Math.PI * 2), d: R(40, o.rad || 110), s: R(.8, 1.4), t0: R(0, .35) }); return add({ life: o.life || .9, draw(c, k, dt, t) { hs.forEach(h => { const lt = (t - h.t0) / .35; if (lt < 0) return; const grow = Math.min(1, lt * 2.5), slap = lt > .5 && lt < 1 ? Math.sin((lt - .5) * Math.PI * 4) * .4 : 0; c.globalAlpha = k > .85 ? (1 - k) / .15 : 1; const hx = x + Math.cos(h.a) * h.d, hy = y + Math.sin(h.a) * h.d * .8; P.hand(c, hx, hy, h.a - Math.PI / 2 + Math.PI + slap, h.s * grow, o.skin || '#f3caa8', o.sleeve || '#5a3c8c', lt > .6); }); if (o.petals && Math.random() < .3) { } } }); },
    bigHand(x, y, o) { o = o || {}; return add({ life: o.life || 1.1, draw(c, k) { const rise = ease.out(Math.min(1, k * 2.5)); const grip = k > .45; c.globalAlpha = k > .85 ? (1 - k) / .15 : 1; P.hand(c, x, y + 180 - rise * 150, 0, (o.s || 5) * (grip ? 1 - (k - .45) * .15 : 1), o.skin || '#f3caa8', o.sleeve || '#3c2463', grip); } }); },
    wave(x1, x2, y, o) { o = o || {}; return add({ life: o.life || .8, draw(c, k, dt, t) { const x = x1 + (x2 - x1) * ease.io(k), d = Math.sign(x2 - x1) || 1, h = (o.h || 160) * Math.sin(Math.min(1, k * 1.2) * Math.PI) + 20; c.globalAlpha = .85 * fade(k, .1, .85); const g = c.createLinearGradient(0, y - h, 0, y + 60); g.addColorStop(0, '#e9fbff'); g.addColorStop(.3, '#4fc3dc'); g.addColorStop(1, '#0e5e80'); c.fillStyle = g; c.beginPath(); c.moveTo(x1, y + 60); for (let xx = x1; d > 0 ? xx <= x : xx >= x; xx += d * 8) { const q = (xx - x1) / ((x - x1) || 1); c.lineTo(xx, y + 60 - Math.pow(q, 3) * h - Math.sin(xx * .05 + t * 8) * 8); } c.lineTo(x, y + 60); c.closePath(); c.fill(); c.fillStyle = '#fff'; for (let i = 0; i < 12; i++) { c.beginPath(); c.arc(x - d * R(0, 30), y + 60 - h + R(-10, 20), R(3, 8), 0, Math.PI * 2); c.fill(); } } }); },
    serpent(x1, y1, x2, y2, o) { o = o || {}; const len = o.len || 420; return add({ life: o.life || 1, draw(c, k, dt, t) { const head = ease.io(Math.min(1, k * 1.15)); const hx = x1 + (x2 - x1) * head, hy = y1 + (y2 - y1) * head, d = Math.sign(x2 - x1) || 1; c.globalAlpha = fade(k, .08, .85); c.lineCap = 'round'; const pts = []; for (let i = 0; i < 30; i++) { const q = i / 29; pts.push([hx - d * q * len, hy + Math.sin(q * 7 - t * 10) * (o.amp || 40) * q + q * 40]); } c.strokeStyle = o.body || '#2f7f6a'; c.lineWidth = o.w || 44; path(c, pts); c.stroke(); c.strokeStyle = o.belly || '#b9e3c6'; c.lineWidth = (o.w || 44) * .3; c.stroke(); c.fillStyle = o.body || '#2f7f6a'; c.beginPath(); c.moveTo(hx + d * 70, hy); c.lineTo(hx - d * 10, hy - 36); c.lineTo(hx - d * 10, hy + 30); c.closePath(); c.fill(); c.fillStyle = o.eye || '#ffd23b'; c.beginPath(); c.arc(hx + d * 18, hy - 12, 6, 0, Math.PI * 2); c.fill(); if (o.fins) { c.fillStyle = o.fin || '#e2554a'; for (let i = 4; i < 28; i += 5) { const p = pts[i]; c.beginPath(); c.moveTo(p[0], p[1] - 18); c.lineTo(p[0] - d * 16, p[1] - 44); c.lineTo(p[0] - d * 26, p[1] - 16); c.fill(); } } } }); },
    hammer(x, y, o) { o = o || {}; return add({ life: o.life || .7, draw(c, k) { const fall = k < .45 ? ease.in(k / .45) : 1; const hy = -80 + (y + 20) * fall; c.globalAlpha = k > .8 ? (1 - k) / .2 : 1; c.fillStyle = '#6b4a2f'; c.fillRect(x - 8, hy - 260, 16, 230); glow(c, '#7fd4ff', 24); c.fillStyle = '#9aa7b8'; c.fillRect(x - 70, hy - 40, 140, 80); c.fillStyle = '#c9d6e6'; c.fillRect(x - 70, hy - 40, 140, 14); c.strokeStyle = '#2e3b4d'; c.lineWidth = 4; c.strokeRect(x - 70, hy - 40, 140, 80); } }); },
    spikes(x, y, o) { o = o || {}; const sp = []; for (let i = 0; i < (o.n || 11); i++) sp.push({ x: x + R(-(o.w || 150), o.w || 150), h: R(60, o.h || 190), w: R(14, 30), d: R(0, .25) }); return add({ life: o.life || 1, draw(c, k, dt, t) { c.globalAlpha = k > .8 ? (1 - k) / .2 : .95; sp.forEach(s => { const g = Math.min(1, Math.max(0, (t - s.d) * 6)); const g2 = c.createLinearGradient(0, y, 0, y - s.h); g2.addColorStop(0, '#5fb8e8'); g2.addColorStop(1, '#f2fcff'); c.fillStyle = g2; glow(c, '#bff0ff', 12); c.beginPath(); c.moveTo(s.x - s.w, y); c.lineTo(s.x, y - s.h * g); c.lineTo(s.x + s.w, y); c.closePath(); c.fill(); }); } }); },
    rays(x, y, o) { o = o || {}; return add({ add: true, life: o.life || 1.2, draw(c, k, dt, t) { c.globalAlpha = fade(k, .15, .7) * .8; c.translate(x, y); c.rotate(t * .8); for (let i = 0; i < 16; i++) { c.rotate(Math.PI / 8); const g = c.createLinearGradient(0, 0, (o.r || 320), 0); g.addColorStop(0, o.c1 || 'rgba(255,255,255,.9)'); g.addColorStop(1, 'rgba(255,240,200,0)'); c.fillStyle = g; c.beginPath(); c.moveTo(0, 0); c.lineTo(o.r || 320, -18); c.lineTo(o.r || 320, 18); c.closePath(); c.fill(); } } }); },
    puffs(x, y, o) { o = o || {}; const ps = []; for (let i = 0; i < (o.n || 14); i++) ps.push({ a: R(0, Math.PI * 2), d: R(30, o.rad || 140), s: R(20, 46) }); return add({ life: o.life || 1.1, draw(c, k) { c.globalAlpha = fade(k, .1, .6) * .9; c.fillStyle = o.color || '#ffffff'; glow(c, o.glow || '#fff', 20); ps.forEach(p => { const e = ease.out(Math.min(1, k * 2)); c.beginPath(); c.arc(x + Math.cos(p.a) * p.d * e, y + Math.sin(p.a) * p.d * e * .7, p.s * (.6 + e * .5), 0, Math.PI * 2); c.fill(); }); } }); },
    pillar(x, y, o) { o = o || {}; return add({ add: true, life: o.life || .7, draw(c, k) { const w = (o.w || 90) * Math.sin(Math.min(1, k * 1.3) * Math.PI); const g = c.createLinearGradient(x - w, 0, x + w, 0); g.addColorStop(0, 'rgba(0,0,0,0)'); g.addColorStop(.35, o.color || '#8fd8ff'); g.addColorStop(.5, '#fff'); g.addColorStop(.65, o.color || '#8fd8ff'); g.addColorStop(1, 'rgba(0,0,0,0)'); c.fillStyle = g; c.fillRect(x - w, -20, w * 2, y + 40); c.globalAlpha = 1 - k; c.fillStyle = '#fff'; c.beginPath(); c.ellipse(x, y + 20, w * 1.6, w * .35, 0, 0, Math.PI * 2); c.fill(); } }); },
    drums(x, y, o) { o = o || {}; return add({ life: o.life || 1, draw(c, k, dt, t) { c.globalAlpha = fade(k, .15, .8); for (let i = 0; i < 4; i++) { const a = t * 3 + i * Math.PI / 2, dx = x + Math.cos(a) * (o.r || 90), dy = y + Math.sin(a) * (o.r || 90) * .45 - 40; glow(c, '#8fd8ff', 16); c.fillStyle = '#d9b35c'; c.beginPath(); c.arc(dx, dy, 22, 0, Math.PI * 2); c.fill(); c.fillStyle = '#1c1c22'; c.font = '900 22px serif'; c.textAlign = 'center'; c.textBaseline = 'middle'; c.fillText('巴', dx, dy + 1); } } }); },
    shield(x, y, o) { o = o || {}; return add({ add: true, life: o.life || 1, draw(c, k, dt, t) { const r = (o.r || 120) * ease.out(Math.min(1, k * 3)); c.globalAlpha = fade(k, .1, .75) * .8; const g = c.createRadialGradient(x - r * .3, y - r * .3, r * .1, x, y, r); g.addColorStop(0, 'rgba(255,255,255,.5)'); g.addColorStop(.7, o.color || 'rgba(90,200,230,.25)'); g.addColorStop(1, o.edge || 'rgba(140,230,255,.9)'); c.fillStyle = g; c.beginPath(); c.arc(x, y, r, 0, Math.PI * 2); c.fill(); } }); },
    wings(x, y, o) { o = o || {}; return add({ life: o.life || 1, draw(c, k, dt, t) { c.globalAlpha = fade(k, .12, .75); const flap = Math.sin(t * 12) * .25; [-1, 1].forEach(sd => { for (let i = 0; i < 7; i++) { const ang = -Math.PI / 2 + sd * (.35 + i * .2 + flap), len = 60 + i * 14; P.hand(c, x + Math.cos(ang) * len * .6, y - 30 + Math.sin(ang) * len * .6, ang + Math.PI / 2, 1.1, o.skin || '#f3caa8', o.sleeve || '#5a3c8c', false); } }); } }); }
  };
  const NOTES = ['♪', '♫', '♬'];
  function i2note(p) { return NOTES[Math.floor(p.s) % 3]; }
  return { add, P, R, clear, ensure, get W() { return W; }, get H() { return H; } };
})();

/* ---------- 角色動作（戰鬥者本身的位移） ---------- */
function moveFighter(side, kind, dist) {
  const el = $('bF' + side), d = side === 'L' ? 1 : -1, D = (dist || 1);
  const K = {
    lunge: [{ transform: 'none' }, { transform: `translateX(${d * 40 * D}%) scale(1.05)`, offset: .35 }, { transform: 'none' }],
    dash: [{ transform: 'none' }, { transform: `translateX(${d * 105}%)`, offset: .3 }, { transform: `translateX(${d * 95}%)`, offset: .65 }, { transform: 'none' }],
    stretch: [{ transform: 'none' }, { transform: `translateX(${d * 12}%) scaleX(1.12)`, offset: .3 }, { transform: 'none' }],
    float: [{ transform: 'none' }, { transform: 'translateY(-10%) scale(1.06)', offset: .4 }, { transform: 'translateY(-10%) scale(1.06)', offset: .7 }, { transform: 'none' }],
    stomp: [{ transform: 'none' }, { transform: 'translateY(-16%)', offset: .35 }, { transform: 'translateY(3%) scaleY(.95)', offset: .55 }, { transform: 'none' }],
    recoil: [{ transform: 'none' }, { transform: `translateX(${-d * 8}%)`, offset: .3 }, { transform: 'none' }],
    shake: [{ transform: 'none' }, { transform: 'translateX(-2%)', offset: .2 }, { transform: 'translateX(2%)', offset: .4 }, { transform: 'translateX(-2%)', offset: .6 }, { transform: 'none' }]
  };
  el.animate(K[kind] || K.lunge, { duration: kind === 'dash' ? 900 : kind === 'float' ? 1100 : 520, easing: 'cubic-bezier(.3,.7,.3,1)' });
}
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

/* ---------- 技能編排：CHOREO[角色][技能序號] ---------- */
/* 每支編排回傳 Promise，於「命中瞬間」結束，之後才計算傷害 */
const CHOREO = {
  luffy: [
    async (A) => { moveFighter(A.S, 'stretch'); SFX.play('whoosh'); FXE.P.arm(A.f.x + A.d * 30, A.f.y - 20, A.t.x - A.d * 40, A.t.y - 20, { life: .5 }); await sleep(240); SFX.play('punch'); FXE.P.burst(A.t.x, A.t.y - 20, { r: 110 }); FXE.P.text(A.t.x, A.t.y - 110, '砰！'); },
    async (A) => { moveFighter(A.S, 'dash'); SFX.play('whoosh'); await sleep(260); for (let i = 0; i < 5; i++) { setTimeout(() => { SFX.play('punch'); FXE.P.burst(A.t.x + FXE.R(-40, 40), A.t.y + FXE.R(-60, 40), { r: 70 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 8, spd: [150, 380], life: [.2, .4], size: [2, 4], colors: ['#fff', '#ffcf5a'], shape: 'spark', add: true }); }, i * 90); } FXE.P.text(A.t.x, A.t.y - 130, '咚咚咚！', { size: 54 }); await sleep(360); },
    async (A) => { moveFighter(A.S, 'float'); SFX.play('drum'); for (let i = 0; i < 3; i++) setTimeout(() => FXE.P.ring(A.f.x, A.f.y, { r1: 170, color: '#9dffb8', life: .6 }), i * 280); FXE.P.particles({ x: A.f.x, y: A.f.y + 60, n: 26, spd: [30, 90], ang: [-2.2, -1], life: [.8, 1.3], size: [8, 16], colors: ['rgba(255,255,255,.6)'], g: -40 }); FXE.P.text(A.f.x, A.f.y - 150, '咚咚…', { size: 44, color: '#d9ffe4' }); await sleep(700); },
    async (A) => { moveFighter(A.S, 'stretch'); SFX.play('dark'); FXE.P.snake(A.f.x + A.d * 30, A.f.y - 20, A.t.x, A.t.y - 10, { life: .75 }); await sleep(440); SFX.play('heavy'); FXE.P.burst(A.t.x, A.t.y, { r: 130, color: 'rgba(255,60,50,.8)' }); FXE.P.ring(A.t.x, A.t.y, { r1: 180, color: '#ff4a3a' }); },
    async (A) => { SFX.play('ult'); FXE.P.flash('#fff', .5, .9); FXE.P.rays(A.f.x, A.f.y - 40, { r: 420 }); FXE.P.puffs(A.f.x, A.f.y, { n: 18, rad: 170, life: 1.3 }); moveFighter(A.S, 'float'); for (let i = 0; i < 4; i++) setTimeout(() => { SFX.play('drum'); FXE.P.ring(A.f.x, A.f.y, { r1: 260, color: '#fff6d8', life: .7 }); }, i * 250); FXE.P.text(A.f.x, A.f.y - 190, '解放的戰士', { size: 50, color: '#fffbe8' }); await sleep(1000); }
  ],
  loki: [
    async (A) => { moveFighter(A.S, 'recoil'); SFX.play('zap'); FXE.P.beam(A.f.x + A.d * 40, A.f.y - 70, A.t.x, A.t.y - 20, { w: 40, c1: '#ffffff', c2: '#5fb8ff', life: .6 }); for (let i = 0; i < 3; i++) setTimeout(() => FXE.P.bolt(A.f.x, A.f.y - 60, A.t.x + FXE.R(-30, 30), A.t.y + FXE.R(-40, 30)), i * 90); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 20, spd: [80, 260], life: [.4, .8], size: [3, 7], colors: ['#dff6ff', '#8fd8ff'], shape: 'shard' }); await sleep(380); SFX.play('hit'); },
    async (A) => { moveFighter(A.S, 'stomp'); SFX.play('whoosh'); FXE.P.hammer(A.t.x, A.t.y, { life: .8 }); await sleep(360); SFX.play('thunder'); shake(); FXE.P.bolt(A.t.x, -20, A.t.x, A.t.y, { w: 10 }); FXE.P.cracks(A.t.x, A.t.y + 60, { n: 7 }); FXE.P.ring(A.t.x, A.t.y + 70, { r1: 220, flat: .3, color: '#bfe8ff' }); FXE.P.text(A.t.x, A.t.y - 150, '轟！'); },
    async (A) => { SFX.play('ice'); FXE.P.tint('#8fd8ff', 1.2, .35); FXE.P.spikes(A.t.x, A.t.y + 110, { n: 14, w: 180, life: 1.2 }); await sleep(300); for (let i = 0; i < 10; i++) setTimeout(() => { FXE.P.bolt(A.t.x + FXE.R(-120, 120), -10, A.t.x + FXE.R(-40, 40), A.t.y + FXE.R(-60, 60), { life: .25 }); if (i % 2) SFX.play('zap'); }, i * 55); await sleep(560); SFX.play('heavy'); },
    async (A) => { moveFighter(A.S, 'lunge'); for (let i = 0; i < 5; i++) setTimeout(() => { SFX.play('zap'); FXE.P.beam(A.f.x, A.f.y - 60 + (i - 2) * 26, A.t.x, A.t.y + (i - 2) * 20, { w: 14, c2: '#b0e4ff', life: .3 }); }, i * 110); await sleep(600); SFX.play('hit'); FXE.P.burst(A.t.x, A.t.y, { r: 120, color: 'rgba(120,200,255,.9)' }); },
    async (A) => { SFX.play('ult'); FXE.P.tint('#bfe8ff', 1.4, .35); FXE.P.serpent(A.f.x - A.d * 200, A.f.y + 40, A.f.x + A.d * 260, A.f.y - 160, { body: '#d8f1ff', belly: '#7fb8e0', eye: '#3fb6ff', fins: true, fin: '#9fd6f5', life: 1.3, len: 480, w: 50 }); FXE.P.particles({ x: A.f.x, y: A.f.y, n: 40, spd: [60, 300], life: [.6, 1.2], size: [3, 8], colors: ['#fff', '#bff0ff'], shape: 'shard', delay: .4 }); moveFighter(A.S, 'float'); await sleep(900); SFX.play('ice'); }
  ],
  crocodile: [
    async (A) => { moveFighter(A.S, 'lunge'); SFX.play('slash'); FXE.P.crescent(A.f.x, A.f.y, A.t.x, A.t.y, { size: 70, life: .4 }); FXE.P.particles({ x: A.f.x, y: A.f.y, n: 30, spd: [200, 500], ang: A.d > 0 ? [-.3, .3] : [Math.PI - .3, Math.PI + .3], life: [.3, .6], size: [2, 4], colors: ['#e7c887', '#b58d5a'] }); await sleep(300); SFX.play('sand'); FXE.P.slash(A.t.x, A.t.y, { color: '#ffe0a0', a: -2.4, span: 2 }); },
    async (A) => { SFX.play('sand'); FXE.P.vortex(A.t.x, A.t.y + 110, { r: 170, flat: .28, color: '#c9a06a', core: 'rgba(90,60,20,.9)', arms: 6, spin: 5, life: 1.1 }); FXE.P.particles({ x: A.t.x, y: A.t.y + 110, n: 50, spd: [120, 360], ang: [-2.6, -.5], life: [.5, 1], size: [2, 5], colors: ['#e7c887', '#b58d5a', '#8a6a3e'], g: 500, delay: .3 }); moveFighter(A.T, 'shake'); await sleep(650); },
    async (A) => { moveFighter(A.S, 'dash'); await sleep(250); for (let i = 0; i < 3; i++) setTimeout(() => { SFX.play('slash'); FXE.P.slash(A.t.x, A.t.y, { color: '#ffd27a', a: -1.2 + i * 1.1, span: 1.4, r: 100 + i * 10, life: .25 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 14, spd: [150, 400], life: [.3, .5], size: [2, 4], colors: ['#e7c887'] }); }, i * 120); await sleep(380); },
    async (A) => { moveFighter(A.S, 'lunge', .6); SFX.play('sand'); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 70, spd: [20, 80], life: [.7, 1.1], size: [2, 5], colors: ['#8fd8ff', '#e7c887', '#a9803e'], toward: { x: A.f.x, y: A.f.y }, pull: 5 }); FXE.P.tint('#c9a06a', .9, .25); await sleep(500); SFX.play('hit'); FXE.P.ring(A.t.x, A.t.y, { r1: 140, color: '#e7c887' }); },
    async (A) => { SFX.play('sand'); FXE.P.tint('#d9b064', 1.4, .4); FXE.P.tornado(A.t.x, A.t.y + 120, { h: 320, w: 150, life: 1.4 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 90, spd: [200, 520], life: [.5, 1.1], size: [2, 5], colors: ['#e7c887', '#b58d5a'], jx: 120, jy: 120, delay: .3 }); await sleep(900); SFX.play('sand'); }
  ],
  blackbeard: [
    async (A) => { SFX.play('dark'); FXE.P.vortex(A.f.x + A.d * 40, A.f.y, { r: 110, color: '#2a1440', core: '#000', arms: 5, spin: 10, life: 1 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 60, spd: [10, 60], life: [.6, 1], size: [3, 7], colors: ['#8a5cd6', '#1b1024', '#e8e4dc'], toward: { x: A.f.x + A.d * 40, y: A.f.y }, pull: 8, jx: 80, jy: 100 }); moveFighter(A.T, 'shake'); await sleep(700); SFX.play('hit'); },
    async (A) => { moveFighter(A.S, 'lunge'); await sleep(200); SFX.play('explode'); shake(); FXE.P.cracks(A.f.x + A.d * 90, A.f.y - 20, { n: 12, len: 320, life: 1.1 }); FXE.P.cracks(A.t.x, A.t.y, { n: 8, len: 200 }); FXE.P.ring(A.t.x, A.t.y, { r1: 260, color: '#f4f7ff', w: 12 }); FXE.P.flash('#fff', .2, .6); FXE.P.text(A.t.x, A.t.y - 140, '轟隆！', { size: 70 }); },
    async (A) => { SFX.play('dark'); FXE.P.vortex(A.f.x, A.f.y + 110, { r: 190, flat: .25, color: '#1b1024', core: '#000', arms: 7, spin: 4, life: 1 }); FXE.P.vortex(A.t.x, A.t.y + 110, { r: 150, flat: .25, color: '#2a1440', core: '#000', arms: 5, spin: -6, life: .9 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 30, spd: [100, 250], life: [.4, .8], size: [3, 6], colors: ['#8a5cd6'], shape: 'shard' }); await sleep(620); SFX.play('hit'); },
    async (A) => { SFX.play('dark'); FXE.P.vortex(A.f.x, A.f.y, { r: 120, color: '#2a1440', core: '#000', life: .5 }); await sleep(400); SFX.play('explode'); shake(); FXE.P.burst(A.f.x + A.d * 80, A.f.y, { r: 260, color: 'rgba(60,20,90,.9)' }); FXE.P.particles({ x: A.f.x, y: A.f.y, n: 50, spd: [300, 700], ang: A.d > 0 ? [-.6, .6] : [Math.PI - .6, Math.PI + .6], life: [.4, .8], size: [4, 10], colors: ['#3a3446', '#6b6457', '#8a5cd6'], shape: 'shard', g: 300 }); await sleep(200); },
    async (A) => { SFX.play('ult'); FXE.P.tint('#140a20', 1.2, .6); FXE.P.vortex(A.f.x, A.f.y, { r: 200, color: '#3a1a5a', core: '#000', arms: 8, spin: 6, life: 1.2 }); moveFighter(A.S, 'float'); await sleep(500); SFX.play('explode'); FXE.P.cracks(A.t.x, A.t.y, { n: 14, len: 300 }); FXE.P.text(A.f.x, A.f.y - 170, '澤哈哈哈！', { size: 54, color: '#e8d8ff' }); await sleep(400); }
  ],
  enel: [
    async (A) => { SFX.play('zap'); FXE.P.drums(A.f.x, A.f.y, { life: .9 }); for (let i = 0; i < 5; i++) setTimeout(() => { SFX.play('zap'); FXE.P.bolt(A.f.x + FXE.R(-60, 60), A.f.y - 100, A.t.x + FXE.R(-50, 50), A.t.y + FXE.R(-50, 40)); }, 120 + i * 90); await sleep(620); SFX.play('hit'); FXE.P.burst(A.t.x, A.t.y, { r: 120, color: 'rgba(140,220,255,.9)' }); },
    async (A) => { SFX.play('heal'); moveFighter(A.S, 'float'); for (let i = 0; i < 6; i++) setTimeout(() => FXE.P.bolt(A.f.x + FXE.R(-60, 60), A.f.y - 120, A.f.x + FXE.R(-40, 40), A.f.y + 80, { color: '#9dffb8', life: .25, amp: 16 }), i * 100); FXE.P.ring(A.f.x, A.f.y, { r1: 160, color: '#9dffb8' }); await sleep(250); SFX.play('zap'); FXE.P.bolt(A.f.x, A.f.y, A.t.x, A.t.y, { color: '#ffe46a', w: 4 }); await sleep(300); },
    async (A) => { SFX.play('zap'); FXE.P.flash('#dff6ff', .25, .6); FXE.P.beam(A.f.x + A.d * 30, A.f.y - 40, A.t.x, A.t.y, { w: 60, c1: '#ffffff', c2: '#ffe46a', life: .55 }); await sleep(300); SFX.play('explode'); FXE.P.burst(A.t.x, A.t.y, { r: 170, color: 'rgba(255,230,120,.9)' }); },
    async (A) => { SFX.play('thunder'); FXE.P.tint('#101830', .9, .5); FXE.P.drums(A.f.x, A.f.y, { life: 1 }); await sleep(380); FXE.P.pillar(A.t.x, A.t.y, { w: 110, color: '#8fd8ff', life: .7 }); FXE.P.bolt(A.t.x, -30, A.t.x, A.t.y, { w: 16 }); shake(); FXE.P.text(A.t.x, A.t.y - 160, '神罰', { size: 76, color: '#dff6ff', stroke: '#0b2236' }); await sleep(250); },
    async (A) => { SFX.play('ult'); FXE.P.tint('#0b1a3a', 1.3, .55); FXE.P.drums(A.f.x, A.f.y - 40, { r: 140, life: 1.3 }); FXE.P.shield(A.f.x, A.f.y, { r: 170, color: 'rgba(90,160,255,.25)', edge: 'rgba(160,220,255,.9)', life: 1.3 }); for (let i = 0; i < 8; i++) setTimeout(() => { SFX.play('zap'); FXE.P.bolt(A.f.x, A.f.y - 40, A.f.x + FXE.R(-260, 260), A.f.y + FXE.R(-200, 120), { life: .3 }); }, i * 110); moveFighter(A.S, 'float'); await sleep(950); }
  ],
  shirahoshi: [
    async (A) => { SFX.play('water'); FXE.P.wave(A.f.x, A.t.x + A.d * 60, A.t.y + 40, { h: 150, life: .8 }); await sleep(250); FXE.P.serpent(A.f.x - A.d * 100, A.t.y + 20, A.t.x + A.d * 40, A.t.y - 30, { fins: true, life: .8 }); await sleep(420); SFX.play('hit'); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 30, spd: [100, 300], ang: [-2.8, -.3], life: [.4, .8], size: [3, 7], colors: ['#e9fbff', '#4fc3dc'], g: 600 }); },
    async (A) => { SFX.play('heal'); for (let i = 0; i < 4; i++) setTimeout(() => FXE.P.ring(A.f.x, A.f.y, { r1: 280, color: i % 2 ? '#ffc0d8' : '#9fe6ff', life: .9, w: 5 }), i * 200); FXE.P.particles({ x: A.f.x, y: A.f.y - 40, n: 14, spd: [40, 110], ang: [-2.6, -.5], life: [1, 1.4], size: [9, 13], colors: ['#ffd9ea', '#bff0ff'], shape: 'note', g: -20 }); moveFighter(A.S, 'float'); await sleep(820); },
    async (A) => { SFX.play('water'); FXE.P.shield(A.f.x, A.f.y, { r: 160, life: 1 }); await sleep(300); FXE.P.serpent(A.f.x - A.d * 60, A.f.y + 50, A.t.x, A.t.y, { body: '#5a7fae', belly: '#d9e8f5', fins: true, fin: '#ffb35c', life: .7, len: 360 }); await sleep(450); SFX.play('hit'); },
    async (A) => { SFX.play('ult'); FXE.P.tint('#0e5e80', 1.3, .35); FXE.P.wave(A.f.x - A.d * 100, A.t.x + A.d * 100, A.t.y + 60, { h: 220, life: 1.1 }); [0, 200, 380].forEach((d, i) => setTimeout(() => { SFX.play('water'); FXE.P.serpent(A.f.x - A.d * 200, A.t.y - 60 + i * 60, A.t.x + A.d * 160, A.t.y - 40 + i * 40, { body: ['#2f7f6a', '#7a3f6a', '#3f5a8a'][i], fins: true, life: .9, len: 480, w: 58 }); }, d)); await sleep(900); SFX.play('heavy'); shake(); }
  ],
  robin: [
    async (A) => { SFX.play('petals'); FXE.P.hands(A.t.x, A.t.y, { n: 16, rad: 120, life: 1 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 26, spd: [40, 160], life: [.7, 1.2], size: [4, 7], colors: ['#ff9ac2', '#ffd9ea'], shape: 'petal', g: 40 }); for (let i = 0; i < 6; i++) setTimeout(() => SFX.play('punch'), 250 + i * 70); await sleep(680); },
    async (A) => { SFX.play('whoosh'); FXE.P.wings(A.f.x, A.f.y, { life: 1.1 }); moveFighter(A.S, 'float'); FXE.P.particles({ x: A.f.x, y: A.f.y, n: 20, spd: [30, 120], life: [.8, 1.2], size: [4, 7], colors: ['#ffb3d1'], shape: 'petal', g: 30 }); await sleep(800); SFX.play('heal'); },
    async (A) => { SFX.play('petals'); FXE.P.particles({ x: A.f.x, y: A.f.y, n: 70, spd: [80, 260], life: [.9, 1.4], size: [5, 9], colors: ['#ff9ac2', '#ffd9ea', '#c58bff'], shape: 'petal', drag: 1.5 }); FXE.P.shield(A.f.x, A.f.y, { r: 150, color: 'rgba(255,150,200,.2)', edge: 'rgba(255,180,220,.85)', life: 1 }); await sleep(700); },
    async (A) => { SFX.play('dark'); FXE.P.tint('#2a0f2a', 1, .35); FXE.P.bigHand(A.t.x, A.t.y + 60, { s: 5.2, life: 1.1 }); FXE.P.particles({ x: A.t.x, y: A.t.y, n: 40, spd: [60, 220], life: [.8, 1.2], size: [5, 9], colors: ['#ff6fa8', '#c58bff'], shape: 'petal', delay: .3 }); await sleep(620); SFX.play('heavy'); FXE.P.text(A.t.x, A.t.y - 150, '開花！', { size: 70, color: '#ffd9ea' }); shake(); },
    async (A) => { SFX.play('ult'); FXE.P.tint('#3c2463', 1.3, .4); FXE.P.bigHand(A.f.x - A.d * 110, A.f.y + 80, { s: 6, life: 1.3 }); FXE.P.bigHand(A.f.x + A.d * 90, A.f.y + 100, { s: 5.2, life: 1.3 }); FXE.P.particles({ x: A.f.x, y: A.f.y, n: 50, spd: [60, 240], life: [1, 1.4], size: [5, 9], colors: ['#ff9ac2', '#c58bff'], shape: 'petal' }); await sleep(1000); }
  ]
};

/* 播放技能：優先用角色專屬編排，否則用原本的通用特效 */
async function playChoreo(side, actor, idx, skill) {
  FXE.ensure();
  const S = side === 'P' ? 'L' : 'R', T = side === 'P' ? 'R' : 'L';
  const f = fighterPoint(S), t = fighterPoint(T);
  const A = { S, T, f, t, d: S === 'L' ? 1 : -1 };
  const fn = CHOREO[actor.id] && CHOREO[actor.id][idx];
  if (fn) { try { await fn(A); } catch (e) { console.warn(e); } }
  else { moveFighter(S, skill.type === 'support' ? 'float' : 'lunge'); playSkillAnimation(side, skill); SFX.play(skill.type === 'support' ? 'buff' : 'whoosh'); await sleep(480); }
}
