/* 技能編排：CHOREO[角色][技能序號]，於「命中瞬間」resolve，之後才結算傷害 */
const X = FXE.P;
const CHOREO = {
  luffy: [
    async A => { moveFighter(A.S, 'stretch'); SFX.play('whoosh'); X.arm(A.f.x + A.d * 30, A.f.y - 20, A.t.x - A.d * 40, A.t.y - 20, { life: .5 }); await sleep(230); SFX.play('punch'); X.text(A.t.x, A.t.y - 120, '砰！'); },
    async A => { moveFighter(A.S, 'dash'); SFX.play('whoosh'); await sleep(250); for (let i = 0; i < 5; i++) setTimeout(() => { SFX.play('punch'); X.arm(A.t.x - A.d * 150, A.t.y - 40 + (i - 2) * 22, A.t.x - A.d * 10, A.t.y + (i - 2) * 26, { life: .22, fist: 18 }); X.glow(A.t.x + FXE.R(-30, 30), A.t.y + FXE.R(-50, 40), { color: '#ffaa5a', r: 80, life: .25 }); }, i * 80); X.text(A.t.x, A.t.y - 140, '咚咚咚咚！', { size: 56 }); await sleep(380); },
    async A => { moveFighter(A.S, 'float'); for (let i = 0; i < 4; i++) setTimeout(() => { SFX.play('drum'); X.ring(A.f.x, A.f.y, { r1: 190, color: '#9dffb8', life: .6 }); }, i * 240); X.particles({ x: A.f.x, y: A.f.y + 80, n: 30, spd: [30, 90], ang: [-2.2, -1], life: [.9, 1.4], size: [14, 26], colors: ['#ffffff'], shape: 'smoke', g: -40 }); X.text(A.f.x, A.f.y - 160, '咚…咚…', { size: 46, color: '#d9ffe4', color2: '#5fd38a' }); await sleep(800); },
    async A => { moveFighter(A.S, 'stretch'); SFX.play('dark'); X.snake(A.f.x + A.d * 30, A.f.y - 20, A.t.x, A.t.y - 10, { life: .8 }); await sleep(420); SFX.play('heavy'); X.cracks(A.t.x, A.t.y, { n: 6, len: 160 }); },
    async A => { SFX.play('ult'); X.flash('#ffffff', .6, .95); X.rays(A.f.x, A.f.y - 40, { r: 480, n: 24 }); X.puffs(A.f.x, A.f.y, { n: 20, rad: 190, life: 1.4 }); moveFighter(A.S, 'float'); for (let i = 0; i < 4; i++) setTimeout(() => { SFX.play('drum'); X.ring(A.f.x, A.f.y, { r1: 300, color: '#fff6d8', life: .7 }); }, i * 250); X.text(A.f.x, A.f.y - 200, '解放的戰士', { size: 54, color: '#fffbe8', color2: '#ffd26c' }); await sleep(1050); }
  ],
  zoro: [
    async A => { moveFighter(A.S, 'dash'); SFX.play('whoosh'); await sleep(300); SFX.play('slash'); X.slash(A.t.x, A.t.y, { a: -2.6, span: 2, r: 110, color: '#9fe8b0' }); X.slash(A.t.x, A.t.y, { a: .6, span: 2, r: 110, color: '#9fe8b0', ccw: true }); await sleep(90); X.slash(A.t.x, A.t.y, { a: -1.6, span: 1.6, r: 130, color: '#ffffff', rot: .6 }); X.text(A.t.x, A.t.y - 130, '鬼斬！', { color: '#d8ffe0', color2: '#3fae6a' }); },
    async A => { SFX.play('whoosh'); X.glow(A.f.x, A.f.y, { color: '#bfe8ff', r: 90, life: .3 }); moveFighter(A.S, 'dash'); await sleep(260); X.beam(A.f.x, A.t.y, A.t.x + A.d * 120, A.t.y, { w: 8, c2: '#e8fff0', life: .25 }); await sleep(180); SFX.play('slash'); X.slash(A.t.x, A.t.y, { a: -.2, span: .6, r: 200, w: 40, color: '#e8fff0', flat: .15, life: .4 }); X.particles({ x: A.t.x, y: A.t.y, n: 20, spd: [100, 300], life: [.3, .6], size: [3, 5], colors: ['#ff4a4a', '#c8322b'], shape: 'dot', g: 500, add: false }); },
    async A => { SFX.play('buff'); moveFighter(A.S, 'float'); X.vortex(A.f.x, A.f.y, { r: 130, color: '#2a1030', core: '#000', arms: 5, spin: 5, rim: '#ff4a6a', life: 1 }); X.particles({ x: A.f.x, y: A.f.y + 40, n: 30, spd: [60, 180], ang: [-2.2, -1], life: [.5, .9], size: [4, 8], colors: ['#ff3b5a', '#1a0a14'], shape: 'ember' }); X.text(A.f.x, A.f.y - 170, '霸氣！', { color: '#ffb0c0', color2: '#c8322b' }); await sleep(800); },
    async A => { SFX.play('whoosh'); moveFighter(A.S, 'leap'); X.tornado(A.f.x + A.d * 120, A.f.y + 120, { smoke: '#dff6e4', line: '#ffffff', h: 300, w: 90, life: .9 }); await sleep(420); for (let i = 0; i < 6; i++) setTimeout(() => { SFX.play('slash'); X.slash(A.t.x, A.t.y, { a: FXE.R(-3, 3), span: 1.8, r: 90 + i * 12, color: i % 2 ? '#9fe8b0' : '#ffffff', life: .25 }); }, i * 55); X.text(A.t.x, A.t.y - 150, '三千世界', { size: 60, color: '#d8ffe0', color2: '#3fae6a' }); await sleep(320); },
    async A => { SFX.play('ult'); X.tint('#1a0a1a', 1.4, .65); X.vortex(A.f.x, A.f.y, { r: 220, color: '#3a0a2a', core: '#000', arms: 9, spin: 3, rim: '#ff2b4a', life: 1.4 }); moveFighter(A.S, 'float'); await sleep(500); X.text(A.f.x, A.f.y - 210, '阿修羅', { size: 72, color: '#ffb0c0', color2: '#8a1a2a' }); for (let i = 0; i < 9; i++) setTimeout(() => { SFX.play('slash'); X.slash(A.t.x, A.t.y, { a: i * .7, span: 1.6, r: 120, w: 22, color: i % 3 ? '#ffffff' : '#ff4a6a', life: .25 }); }, 150 + i * 60); await sleep(720); }
  ],
  sanji: [
    async A => { moveFighter(A.S, 'leap'); SFX.play('whoosh'); await sleep(330); SFX.play('punch'); X.slash(A.t.x, A.t.y - 40, { a: -3, span: 2.4, r: 90, w: 30, color: '#ffe0a0', flat: .5 }); X.text(A.t.x, A.t.y - 140, '首肉！', { color: '#fff4c8', color2: '#e8a03a' }); },
    async A => { moveFighter(A.S, 'dash'); X.flames(A.f.x, A.f.y, { n: 40, jx: 40 }); SFX.play('whoosh'); await sleep(280); SFX.play('explode'); X.slash(A.t.x, A.t.y, { a: -2.8, span: 2.6, r: 120, w: 36, color: '#ff7a2a' }); X.flames(A.t.x, A.t.y, { n: 60, jx: 70 }); X.glow(A.t.x, A.t.y, { color: '#ff7a2a', r: 180, life: .5 }); X.text(A.t.x, A.t.y - 150, '惡魔風腳', { size: 58, color: '#ffe27a', color2: '#ff3a1a' }); },
    async A => { SFX.play('heal'); moveFighter(A.S, 'float'); X.particles({ x: A.f.x, y: A.f.y + 20, n: 30, spd: [20, 80], ang: [-2.6, -.5], life: [.9, 1.4], size: [10, 20], colors: ['#ffffff'], shape: 'smoke', g: -30 }); X.particles({ x: A.f.x, y: A.f.y, n: 24, spd: [50, 140], life: [.6, 1], size: [3, 6], colors: ['#ffe27a', '#9dffb8'], g: -40 }); X.text(A.f.x, A.f.y - 160, '開飯了！', { size: 52, color: '#fffbe8', color2: '#5fd38a' }); await sleep(800); },
    async A => { moveFighter(A.S, 'leap'); SFX.play('whoosh'); for (let i = 0; i < 4; i++) setTimeout(() => X.ring(A.f.x + A.d * (40 + i * 60), A.f.y - 60 - i * 20, { r1: 50, flat: .3, color: '#ffffff', life: .3 }), i * 70); await sleep(340); for (let i = 0; i < 4; i++) setTimeout(() => { SFX.play('punch'); X.slash(A.t.x, A.t.y + (i - 1.5) * 30, { a: -3 + i, span: 2, r: 90, w: 24, color: '#ffe0a0', life: .22 }); }, i * 80); await sleep(300); },
    async A => { SFX.play('ult'); X.tint('#0a1a3a', 1.3, .55); X.flames(A.f.x, A.f.y, { n: 90, jx: 70, colors: ['#5fb8ff', '#bff0ff', '#2a6aff'] }); moveFighter(A.S, 'float'); X.glow(A.f.x, A.f.y, { color: '#5fb8ff', r: 220, life: 1.2, hold: true }); await sleep(600); moveFighter(A.S, 'dash'); await sleep(260); SFX.play('explode'); X.slash(A.t.x, A.t.y, { a: -3, span: 3, r: 140, w: 44, color: '#5fb8ff' }); X.flames(A.t.x, A.t.y, { n: 70, jx: 80, colors: ['#5fb8ff', '#bff0ff'] }); X.text(A.t.x, A.t.y - 160, '魔神風腳', { size: 64, color: '#dff6ff', color2: '#2a6aff' }); }
  ],
  yamato: [
    async A => { moveFighter(A.S, 'dash'); SFX.play('whoosh'); await sleep(270); for (let i = 0; i < 4; i++) setTimeout(() => { SFX.play('hit'); X.slash(A.t.x, A.t.y, { a: -2.4 + i * 1.3, span: 1.6, r: 100, w: 30, color: '#bff0ff', life: .24 }); X.particles({ x: A.t.x, y: A.t.y, n: 10, spd: [120, 300], life: [.3, .6], size: [4, 7], colors: ['#e8faff', '#8fd8ff'], shape: 'shard', add: false }); }, i * 85); X.text(A.t.x, A.t.y - 140, '冰牙！', { color: '#e8faff', color2: '#3fa8e8' }); await sleep(320); },
    async A => { SFX.play('dark'); X.vortex(A.f.x + A.d * 30, A.f.y, { r: 90, color: '#5a1a8a', core: '#1a0a2a', rim: '#c58bff', arms: 4, spin: 10, life: .5 }); for (let i = 0; i < 3; i++) setTimeout(() => X.bolt(A.f.x, A.f.y - 60, A.f.x + A.d * FXE.R(40, 120), A.f.y + FXE.R(-60, 60), { color: '#c58bff', life: .2 }), i * 80); await sleep(300); moveFighter(A.S, 'dash'); await sleep(250); SFX.play('explode'); X.bolt(A.f.x, A.t.y, A.t.x, A.t.y, { color: '#c58bff', w: 10, amp: 20 }); X.cracks(A.t.x, A.t.y, { n: 8, color: '#e8d8ff' }); X.text(A.t.x, A.t.y - 150, '雷鳴八卦', { size: 60, color: '#f0e0ff', color2: '#8a3aff' }); },
    async A => { SFX.play('buff'); moveFighter(A.S, 'recoil'); X.beam(A.f.x, A.f.y - 30, A.t.x, A.t.y - 30, { w: 10, c2: '#ffffff', life: .35 }); X.particles({ x: A.f.x, y: A.f.y, n: 30, spd: [60, 200], life: [.5, 1], size: [3, 6], colors: ['#8a5cd6', '#ffffff'], toward: { x: A.t.x, y: A.t.y }, pull: 4 }); for (let i = 0; i < 3; i++) setTimeout(() => X.ring(A.f.x, A.f.y, { r1: 170, color: '#ffe27a', life: .5 }), i * 150); X.text(A.f.x, A.f.y - 160, '鳴鏑', { size: 54, color: '#fffbe8', color2: '#e8c170' }); await sleep(700); },
    async A => { SFX.play('ice'); X.shield(A.f.x, A.f.y, { r: 170, edge: '#bff0ff', life: 1.1 }); X.spikes(A.f.x, A.f.y + 120, { n: 8, w: 120, h: 180, life: 1 }); await sleep(420); moveFighter(A.S, 'lunge'); SFX.play('hit'); X.slash(A.t.x, A.t.y, { a: -2.5, span: 2, r: 110, color: '#bff0ff' }); },
    async A => { SFX.play('ult'); X.tint('#dff6ff', 1.4, .45); X.particles({ x: FXE.W / 2, y: -20, n: 90, spd: [80, 240], ang: [1.2, 2], life: [1, 1.6], size: [3, 6], colors: ['#ffffff', '#dff6ff'], shape: 'snow', jx: FXE.W / 2 }); X.flames(A.f.x, A.f.y, { n: 80, jx: 80, colors: ['#bff0ff', '#ffffff', '#6fd3ff'] }); moveFighter(A.S, 'float'); X.glow(A.f.x, A.f.y, { color: '#8fd8ff', r: 240, life: 1.3, hold: true }); await sleep(700); X.claws(A.t.x, A.t.y, { color: '#e8faff' }); X.spikes(A.t.x, A.t.y + 110, { n: 12, w: 160, life: 1 }); X.text(A.f.x, A.f.y - 210, '大口真神', { size: 64, color: '#ffffff', color2: '#6fd3ff' }); await sleep(250); }
  ],
  loki: [
    async A => { moveFighter(A.S, 'recoil'); SFX.play('zap'); X.beam(A.f.x + A.d * 40, A.f.y - 70, A.t.x, A.t.y - 20, { w: 44, c2: '#5fb8ff', life: .6 }); for (let i = 0; i < 3; i++) setTimeout(() => X.bolt(A.f.x, A.f.y - 60, A.t.x + FXE.R(-30, 30), A.t.y + FXE.R(-40, 30)), i * 90); X.particles({ x: A.t.x, y: A.t.y, n: 20, spd: [80, 260], life: [.4, .8], size: [4, 8], colors: ['#dff6ff', '#8fd8ff'], shape: 'shard', add: false }); await sleep(380); },
    async A => { moveFighter(A.S, 'stomp'); SFX.play('whoosh'); X.hammer(A.t.x, A.t.y, { life: .85 }); await sleep(350); SFX.play('thunder'); shake(); X.bolt(A.t.x, -20, A.t.x, A.t.y, { w: 12 }); X.cracks(A.t.x, A.t.y + 60, { n: 8 }); X.ring(A.t.x, A.t.y + 70, { r1: 260, flat: .3, color: '#bfe8ff' }); X.text(A.t.x, A.t.y - 160, '轟！'); },
    async A => { SFX.play('ice'); X.tint('#8fd8ff', 1.2, .35); X.spikes(A.t.x, A.t.y + 110, { n: 16, w: 200, life: 1.2 }); await sleep(280); for (let i = 0; i < 10; i++) setTimeout(() => { X.bolt(A.t.x + FXE.R(-140, 140), -10, A.t.x + FXE.R(-40, 40), A.t.y + FXE.R(-60, 60), { life: .25 }); if (i % 2) SFX.play('zap'); }, i * 55); await sleep(560); SFX.play('heavy'); },
    async A => { moveFighter(A.S, 'lunge'); for (let i = 0; i < 5; i++) setTimeout(() => { SFX.play('zap'); X.beam(A.f.x, A.f.y - 60 + (i - 2) * 26, A.t.x, A.t.y + (i - 2) * 20, { w: 14, c2: '#b0e4ff', life: .3 }); }, i * 110); await sleep(600); SFX.play('hit'); },
    async A => { SFX.play('ult'); X.tint('#bfe8ff', 1.4, .35); X.serpent(A.f.x - A.d * 200, A.f.y + 40, A.f.x + A.d * 280, A.f.y - 160, { body: '#8fd8ff', belly: '#e8faff', eye: '#ffffff', horn: true, fins: true, fin: '#9fd6f5', life: 1.3, len: 500, w: 54 }); X.particles({ x: A.f.x, y: A.f.y, n: 40, spd: [60, 300], life: [.6, 1.2], size: [4, 9], colors: ['#ffffff', '#bff0ff'], shape: 'shard', delay: .4, add: false }); moveFighter(A.S, 'float'); await sleep(950); SFX.play('ice'); }
  ],
  crocodile: [
    async A => { moveFighter(A.S, 'lunge'); SFX.play('slash'); X.crescent(A.f.x, A.f.y, A.t.x, A.t.y, { size: 76, life: .4 }); X.particles({ x: A.f.x, y: A.f.y, n: 40, spd: [200, 500], ang: A.d > 0 ? [-.3, .3] : [Math.PI - .3, Math.PI + .3], life: [.3, .6], size: [2, 4], colors: ['#e7c887', '#b58d5a'], shape: 'sand' }); await sleep(300); SFX.play('sand'); X.slash(A.t.x, A.t.y, { color: '#ffe0a0', a: -2.4, span: 2 }); },
    async A => { SFX.play('sand'); X.vortex(A.t.x, A.t.y + 110, { r: 180, flat: .28, color: '#c9a06a', core: '#5a3a14', arms: 7, spin: 5, rim: '#ffe0a0', life: 1.1 }); X.particles({ x: A.t.x, y: A.t.y + 110, n: 60, spd: [120, 360], ang: [-2.6, -.5], life: [.5, 1], size: [2, 5], colors: ['#e7c887', '#b58d5a', '#8a6a3e'], shape: 'sand', g: 500, delay: .3 }); moveFighter(A.T, 'shake'); await sleep(650); },
    async A => { moveFighter(A.S, 'dash'); await sleep(250); for (let i = 0; i < 3; i++) setTimeout(() => { SFX.play('slash'); X.slash(A.t.x, A.t.y, { color: '#ffd27a', a: -1.2 + i * 1.1, span: 1.4, r: 100 + i * 12, life: .25 }); }, i * 120); await sleep(380); },
    async A => { moveFighter(A.S, 'lunge', .6); SFX.play('sand'); X.particles({ x: A.t.x, y: A.t.y, n: 70, spd: [20, 80], life: [.7, 1.1], size: [3, 6], colors: ['#8fd8ff', '#bfe8ff'], toward: { x: A.f.x, y: A.f.y }, pull: 5, jx: 60, jy: 80 }); X.tint('#c9a06a', .9, .25); await sleep(520); SFX.play('hit'); },
    async A => { SFX.play('sand'); X.tint('#d9b064', 1.4, .4); X.tornado(A.t.x, A.t.y + 120, { h: 340, w: 160, life: 1.4 }); X.particles({ x: A.t.x, y: A.t.y, n: 120, spd: [200, 520], life: [.5, 1.1], size: [2, 4], colors: ['#e7c887', '#b58d5a'], shape: 'sand', jx: 120, jy: 120, delay: .3 }); await sleep(900); SFX.play('sand'); }
  ],
  blackbeard: [
    async A => { SFX.play('dark'); X.vortex(A.f.x + A.d * 40, A.f.y, { r: 120, color: '#2a1440', core: '#000', arms: 6, spin: 10, rim: '#8a5cd6', life: 1 }); X.particles({ x: A.t.x, y: A.t.y, n: 60, spd: [10, 60], life: [.6, 1], size: [10, 18], colors: ['#2a1440', '#1b1024'], shape: 'smoke', toward: { x: A.f.x + A.d * 40, y: A.f.y }, pull: 8, jx: 80, jy: 100 }); moveFighter(A.T, 'shake'); await sleep(720); },
    async A => { moveFighter(A.S, 'lunge'); await sleep(200); SFX.play('explode'); shake(); X.cracks(A.f.x + A.d * 90, A.f.y - 20, { n: 14, len: 340, life: 1.1 }); X.cracks(A.t.x, A.t.y, { n: 9, len: 220 }); X.flash('#ffffff', .2, .5); X.text(A.t.x, A.t.y - 150, '轟隆！', { size: 74 }); },
    async A => { SFX.play('dark'); X.vortex(A.f.x, A.f.y + 110, { r: 200, flat: .25, color: '#1b1024', core: '#000', arms: 7, spin: 4, rim: '#8a5cd6', life: 1 }); X.vortex(A.t.x, A.t.y + 110, { r: 160, flat: .25, color: '#2a1440', core: '#000', arms: 5, spin: -6, rim: '#8a5cd6', life: .9 }); await sleep(620); SFX.play('hit'); },
    async A => { SFX.play('dark'); X.vortex(A.f.x, A.f.y, { r: 130, color: '#2a1440', core: '#000', rim: '#8a5cd6', life: .5 }); await sleep(400); SFX.play('explode'); shake(); X.glow(A.f.x + A.d * 80, A.f.y, { color: '#6a2aaa', r: 280, life: .6 }); X.particles({ x: A.f.x, y: A.f.y, n: 50, spd: [300, 700], ang: A.d > 0 ? [-.6, .6] : [Math.PI - .6, Math.PI + .6], life: [.4, .8], size: [5, 11], colors: ['#3a3446', '#6b6457', '#8a5cd6'], shape: 'shard', g: 300, add: false }); await sleep(200); },
    async A => { SFX.play('ult'); X.tint('#140a20', 1.2, .6); X.vortex(A.f.x, A.f.y, { r: 220, color: '#3a1a5a', core: '#000', arms: 9, spin: 6, rim: '#b58cff', life: 1.2 }); moveFighter(A.S, 'float'); await sleep(500); SFX.play('explode'); X.cracks(A.t.x, A.t.y, { n: 14, len: 300 }); X.text(A.f.x, A.f.y - 180, '澤哈哈哈！', { size: 56, color: '#e8d8ff', color2: '#8a5cd6' }); await sleep(400); }
  ],
  enel: [
    async A => { SFX.play('zap'); X.drums(A.f.x, A.f.y, { life: .9 }); for (let i = 0; i < 5; i++) setTimeout(() => { SFX.play('zap'); X.bolt(A.f.x + FXE.R(-60, 60), A.f.y - 100, A.t.x + FXE.R(-50, 50), A.t.y + FXE.R(-50, 40)); }, 120 + i * 90); await sleep(620); },
    async A => { SFX.play('heal'); moveFighter(A.S, 'float'); for (let i = 0; i < 6; i++) setTimeout(() => X.bolt(A.f.x + FXE.R(-60, 60), A.f.y - 120, A.f.x + FXE.R(-40, 40), A.f.y + 80, { color: '#9dffb8', life: .25, amp: 16 }), i * 100); X.ring(A.f.x, A.f.y, { r1: 170, color: '#9dffb8' }); await sleep(260); SFX.play('zap'); X.bolt(A.f.x, A.f.y, A.t.x, A.t.y, { color: '#ffe46a', w: 5 }); await sleep(300); },
    async A => { SFX.play('zap'); X.flash('#dff6ff', .25, .6); X.beam(A.f.x + A.d * 30, A.f.y - 40, A.t.x, A.t.y, { w: 64, c2: '#ffe46a', life: .55 }); await sleep(300); SFX.play('explode'); },
    async A => { SFX.play('thunder'); X.tint('#101830', .9, .55); X.drums(A.f.x, A.f.y, { life: 1 }); await sleep(380); X.pillar(A.t.x, A.t.y, { w: 120, color: '#8fd8ff', life: .75 }); X.bolt(A.t.x, -30, A.t.x, A.t.y, { w: 18 }); shake(); X.text(A.t.x, A.t.y - 170, '神罰', { size: 80, color: '#dff6ff', color2: '#3f8aff', stroke: '#0b2236' }); await sleep(250); },
    async A => { SFX.play('ult'); X.tint('#0b1a3a', 1.3, .55); X.drums(A.f.x, A.f.y - 40, { r: 150, life: 1.3 }); X.shield(A.f.x, A.f.y, { r: 180, edge: '#a0dcff', life: 1.3 }); for (let i = 0; i < 8; i++) setTimeout(() => { SFX.play('zap'); X.bolt(A.f.x, A.f.y - 40, A.f.x + FXE.R(-280, 280), A.f.y + FXE.R(-200, 120), { life: .3 }); }, i * 110); moveFighter(A.S, 'float'); await sleep(950); }
  ],
  shirahoshi: [
    async A => { SFX.play('water'); X.wave(A.f.x, A.t.x + A.d * 60, A.t.y + 40, { h: 160, life: .8 }); await sleep(250); X.serpent(A.f.x - A.d * 100, A.t.y + 20, A.t.x + A.d * 40, A.t.y - 30, { fins: true, life: .8 }); await sleep(420); X.particles({ x: A.t.x, y: A.t.y, n: 30, spd: [100, 300], ang: [-2.8, -.3], life: [.4, .8], size: [3, 6], colors: ['#e9fbff', '#4fc3dc'], g: 600 }); },
    async A => { SFX.play('heal'); for (let i = 0; i < 4; i++) setTimeout(() => X.ring(A.f.x, A.f.y, { r1: 300, color: i % 2 ? '#ffc0d8' : '#9fe6ff', life: .9, w: 6 }), i * 200); X.particles({ x: A.f.x, y: A.f.y - 40, n: 14, spd: [40, 110], ang: [-2.6, -.5], life: [1, 1.4], size: [9, 13], colors: ['#ffd9ea', '#bff0ff'], shape: 'note', g: -20, add: false }); moveFighter(A.S, 'float'); await sleep(820); },
    async A => { SFX.play('water'); X.shield(A.f.x, A.f.y, { r: 170, life: 1 }); await sleep(300); X.serpent(A.f.x - A.d * 60, A.f.y + 50, A.t.x, A.t.y, { body: '#5a7fae', belly: '#d9e8f5', fins: true, fin: '#ffb35c', life: .7, len: 380 }); await sleep(450); },
    async A => { SFX.play('ult'); X.tint('#0e5e80', 1.3, .35); X.wave(A.f.x - A.d * 100, A.t.x + A.d * 100, A.t.y + 60, { h: 240, life: 1.1 }); [0, 200, 380].forEach((d, i) => setTimeout(() => { SFX.play('water'); X.serpent(A.f.x - A.d * 200, A.t.y - 60 + i * 60, A.t.x + A.d * 160, A.t.y - 40 + i * 40, { body: ['#2f7f6a', '#7a3f6a', '#3f5a8a'][i], fins: true, life: .9, len: 500, w: 60 }); }, d)); await sleep(900); SFX.play('heavy'); shake(); }
  ],
  robin: [
    async A => { SFX.play('petals'); X.hands(A.t.x, A.t.y, { n: 16, rad: 120, life: 1 }); X.particles({ x: A.t.x, y: A.t.y, n: 26, spd: [40, 160], life: [.7, 1.2], size: [5, 8], colors: ['#ff9ac2', '#ffd9ea'], shape: 'petal', g: 40 }); for (let i = 0; i < 6; i++) setTimeout(() => SFX.play('punch'), 250 + i * 70); await sleep(700); },
    async A => { SFX.play('whoosh'); X.wings(A.f.x, A.f.y, { life: 1.1 }); moveFighter(A.S, 'float'); X.particles({ x: A.f.x, y: A.f.y, n: 20, spd: [30, 120], life: [.8, 1.2], size: [5, 8], colors: ['#ffb3d1'], shape: 'petal', g: 30 }); await sleep(800); SFX.play('heal'); },
    async A => { SFX.play('petals'); X.particles({ x: A.f.x, y: A.f.y, n: 80, spd: [80, 260], life: [.9, 1.4], size: [5, 10], colors: ['#ff9ac2', '#ffd9ea', '#c58bff'], shape: 'petal', drag: 1.5 }); X.shield(A.f.x, A.f.y, { r: 160, edge: '#ffb4dc', life: 1 }); await sleep(700); },
    async A => { SFX.play('dark'); X.tint('#2a0f2a', 1, .35); X.bigHand(A.t.x, A.t.y + 60, { s: 5.2, life: 1.1 }); X.particles({ x: A.t.x, y: A.t.y, n: 40, spd: [60, 220], life: [.8, 1.2], size: [5, 9], colors: ['#ff6fa8', '#c58bff'], shape: 'petal', delay: .3 }); await sleep(620); SFX.play('heavy'); X.text(A.t.x, A.t.y - 160, '開花！', { size: 72, color: '#ffe0ee', color2: '#ff5a9a' }); shake(); },
    async A => { SFX.play('ult'); X.tint('#3c2463', 1.3, .4); X.bigHand(A.f.x - A.d * 110, A.f.y + 80, { s: 6, life: 1.3 }); X.bigHand(A.f.x + A.d * 90, A.f.y + 100, { s: 5.2, life: 1.3 }); X.particles({ x: A.f.x, y: A.f.y, n: 50, spd: [60, 240], life: [1, 1.4], size: [5, 9], colors: ['#ff9ac2', '#c58bff'], shape: 'petal' }); await sleep(1000); }
  ]
};

async function playChoreo(side, actor, idx, skill) {
  FXE.ensure();
  const S = side === 'P' ? 'L' : 'R', T = side === 'P' ? 'R' : 'L';
  const A = { S, T, f: fighterPoint(S), t: fighterPoint(T), d: S === 'L' ? 1 : -1 };
  const fn = idx >= 0 && CHOREO[actor.id] && CHOREO[actor.id][idx];
  if (fn) { try { await fn(A); } catch (e) { console.warn(e); } }
  else { moveFighter(S, skill.type === 'support' ? 'float' : 'lunge'); SFX.play(skill.type === 'support' ? 'buff' : 'whoosh'); await sleep(300); SFX.play('punch'); }
}

/* 初登場魯夫：沿用橡膠系的手臂特效，另加鞭腿、風船與巨人斧 */
CHOREO.luffy0 = [
  CHOREO.luffy[0],
  async A => { moveFighter(A.S, 'stretch'); SFX.play('whoosh'); X.slash(A.t.x, A.t.y + 30, { r: 150, a: A.d > 0 ? -2.6 : -.6, span: 2.2, color: '#f0b98a', w: 16, life: .35 }); await sleep(220); SFX.play('hit'); X.burst(A.t.x, A.t.y + 20, { r: 110 }); X.text(A.t.x, A.t.y - 120, '啪！', { size: 60 }); },
  CHOREO.luffy[1],
  async A => { SFX.play('buff'); moveFighter(A.S, 'float'); X.shield(A.f.x, A.f.y + 10, { r: 150, edge: '#ffb35c', life: 1.1 }); X.text(A.f.x, A.f.y - 160, '噗～！', { size: 58, color: '#fff1d6' }); await sleep(800); },
  async A => { SFX.play('ult'); moveFighter(A.S, 'stomp'); X.arm(A.f.x + A.d * 20, A.f.y - 40, A.t.x, -60, { life: .45, skin: '#f0b98a', sleeve: '#3f6fb8' }); await sleep(420); X.arm(A.t.x, -60, A.t.x, A.t.y, { life: .35, skin: '#f0b98a', sleeve: '#3f6fb8', fist: 26 }); await sleep(200); SFX.play('heavy'); shake(); X.burst(A.t.x, A.t.y, { r: 180 }); X.cracks(A.t.x, A.t.y + 70, { n: 8 }); X.text(A.t.x, A.t.y - 150, '轟！', { size: 76 }); }
];
